// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHt6XbhZHKIfcgEQRGyTV8l6TuAU4UDA',
    appId: '1:589685755378:web:9e89b0f38fc2f263792f6b',
    messagingSenderId: '589685755378',
    projectId: 'story-mobile-app-oua',
    authDomain: 'story-mobile-app-oua.firebaseapp.com',
    storageBucket: 'story-mobile-app-oua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIRiT-jPBImKv0aia9R47t6nvaNn5cZk',
    appId: '1:589685755378:android:eead69a6160278c3792f6b',
    messagingSenderId: '589685755378',
    projectId: 'story-mobile-app-oua',
    storageBucket: 'story-mobile-app-oua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbRna3Eb8tZecQ0rH3CySZ4PJAM3Gi5Q',
    appId: '1:589685755378:ios:c3a8640680cee492792f6b',
    messagingSenderId: '589685755378',
    projectId: 'story-mobile-app-oua',
    storageBucket: 'story-mobile-app-oua.appspot.com',
    iosBundleId: 'com.example.aijam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvbRna3Eb8tZecQ0rH3CySZ4PJAM3Gi5Q',
    appId: '1:589685755378:ios:c3a8640680cee492792f6b',
    messagingSenderId: '589685755378',
    projectId: 'story-mobile-app-oua',
    storageBucket: 'story-mobile-app-oua.appspot.com',
    iosBundleId: 'com.example.aijam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfHt6XbhZHKIfcgEQRGyTV8l6TuAU4UDA',
    appId: '1:589685755378:web:d6eb9be80e524412792f6b',
    messagingSenderId: '589685755378',
    projectId: 'story-mobile-app-oua',
    authDomain: 'story-mobile-app-oua.firebaseapp.com',
    storageBucket: 'story-mobile-app-oua.appspot.com',
  );
}
